### PR TITLE
add: delete buttons and delete handler

### PR DESCRIPTION
**Pull request by Brook4747**
I added three delete buttons and delete handler according to Ricky's recommendation and task requirements.

### CODE REVIEW

**Comment by rickydodd** [comment]
[Fix file deletion method.](https://trello.com/c/7tuna2st/221-fix-file-deletion-method)

**Comment by rickydodd** [comment]
[Create deletion buttons for thoth-tech/ChatHistoryDisplayer.](https://trello.com/c/Os8d8qyv/215-create-deletion-buttons-for-thoth-tech-chathistorydisplayer)

**Comment by rickydodd** [comment]
[Create a function that handles sending delete requests to the ChatHistoryDisplayer API.](https://trello.com/c/fb3TxdYS/216-create-a-function-that-handles-sending-delete-requests-to-the-chathistorydisplayer-api)

**Comment by rickydodd** [comment]
I reviewed the code and it works. It's functionally correct and the only issue (where this issue is outside the scope of this pull request, anyway, but it does impact it) is fixed with this PR: https://github.com/thoth-tech/ChatHistoryDisplayer/pull/11

**Review by lst97 — APPROVED** [review]

**Pull request merged**
